name: Deploy to S3 + CloudFront

on:
  push:
    branches: ['main']
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  S3_BUCKET: ${{ vars.S3_BUCKET }}
  CF_DISTRIBUTION_ID: ${{ vars.CF_DISTRIBUTION_ID }}
  ROLE_ARN: ${{ vars.ROLE_ARN }}
  BUILD_DIR: ${{ vars.BUILD_DIR || 'dist' }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Upload HTML and non-asset files (short cache)
        run: |
          aws s3 sync ${BUILD_DIR} "s3://${S3_BUCKET}" \
            --delete \
            --exclude "assets/*" \
            --cache-control "no-cache, no-store, must-revalidate"

      - name: Upload assets (long cache, immutable)
        run: |
          if [ -d "${BUILD_DIR}/assets" ]; then
            aws s3 sync dist/assets "s3://${S3_BUCKET}/assets" \
              --delete \
              --cache-control "public, max-age=31536000, immutable"
          fi

      - name: Create CloudFront invalidation
        run: |
          aws cloudfront create-invalidation \
            --distribution-id "${CF_DISTRIBUTION_ID}" \
            --paths "/*"
